#spring.datasource.url=jdbc:postgresql://db:5432/
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.hikari.maximum-pool-size=5
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.jdbc.batch_size=1000
#spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  #spring.jpa.properties.hibernate.format_sql=true
#  #spring.jpa.properties.hibernate.generate_statistics=true
#  #spring.jpa.properties.hibernate.show_sql=false
#
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB
#spring.datasource.hikari.data-source-properties.useUnicode=true
#spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
##spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

jwt:
    secret: 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
spring:
    profiles:
      active: dev
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB