spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wbsb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        characterEncoding: ISO-8859-1
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        generate_statistics: true
#        format_sql: true
#        show_sql: true
