spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wbsb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        characterEncoding: ISO-8859-1
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 361463634645-k1brd3lmdc06n66761o6hmi903onipaj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/google"
